language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE='PurBeurre_WebApp.settings.travis'

services:
  - postgresql

script:
  - python ./manage.py test

addons:
  firefox: '49.0'

branches:
  only:
    - staging