language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env: 
  - DJANGO_SETTINGS_MODULE='PurBeurre_WebApp.settings.travis'
  - MOZ_HEADLESS=1

services:
  - postgresql

script:
  - python ./manage.py test

addons:
  firefox: latest

branches:
  only:
    - staging